### ISSUE TITLE
Locally hosted, some widget API calls fail

### ISSUE THREAD

**Issue by Logvin** [allister-grange/startertab#38]
I am running startertab on my own personal website. Some widgets are working great, like the Reddit one, and some do not.

Not working: Stocks, Weather

![image](https://user-images.githubusercontent.com/13814907/221028313-2a75babf-c5e5-4d86-8adf-89ea690d8f49.png)

**Comment by allister-grange** [comment]
Hey @Logvin, the issue is because you are missing environment variables for the API routes that call the third party APIs.

You'll either need to sign up for the services and get an API key/secret for each of the services you want, or you can just use StarterTab at https://startertab.com. The site should still be customisable to your needs.

The README.md has an up to date list all of the environment variables you need, here is the list currently:

```
STRAVA_CLIENT_ID=<YOUR_SECRET_HERE>
STRAVA_SECRET<YOUR_SECRET_HERE>
WEATHERAPI_TOKEN<YOUR_SECRET_HERE>
SPOTIFY_CLIENT_ID<YOUR_SECRET_HERE>
SPOTIFY_CLIENT_SECRET<YOUR_SECRET_HERE>
FINNHUB_SECRET<YOUR_SECRET_HERE>
TWITTER_CLIENT_ID<YOUR_SECRET_HERE>
TWITTER_CLIENT_SECRET<YOUR_SECRET_HERE>
TWITTER_CODE_CHALLENGE_KEY<YOUR_SECRET_HERE>
TOKEN_ENCRYPT_KEY<YOUR_SECRET_HERE>
OUTLOOK_CLIENT_ID<YOUR_SECRET_HERE>
OUTLOOK_CLIENT_SECRET<YOUR_SECRET_HERE>
GOOGLE_CLIENT_ID<YOUR_SECRET_HERE>
GOOGLE_CLIENT_SECRET<YOUR_SECRET_HERE>
```
