### ISSUE TITLE
Google Meetings Tile Does Not Work

### ISSUE THREAD

**Issue by vayunalapati** [allister-grange/startertab#52]
The Google Meetings tile seems to be permanently broken even after clearing data
<img width="523" alt="image" src="https://github.com/allister-grange/startertab/assets/77701570/4b9eb9f0-68db-4e27-b326-748a3f8bcc3d">

**Comment by allister-grange** [comment]
Sorry about the issue! 

I'm currently on holiday - I'll get around to this when I can.

**Comment by allister-grange** [comment]
Hey @vayunalapati looks like your data might be _really_ corrupted.

I'm sorry about this (as it will clear all of your themes out), but if you delete the `user_settings` in your local storage from the browser, this should fix the issue. Otherwise, you could try manually copy/pasting the value for `user_settings` out and remove all reference to the Google Meetings Tiles within the json.

Let me know how you go!

<img width="1458" alt="image" src="https://github.com/allister-grange/startertab/assets/18430086/69611d01-0616-4748-89a3-34286586c99b">

**Comment by vayunalapati** [comment]
> Hey @vayunalapati looks like your data might be _really_ corrupted.
> 
> I'm sorry about this (as it will clear all of your themes out), but if you delete the `user_settings` in your local storage from the browser, this should fix the issue. Otherwise, you could try manually copy/pasting the value for `user_settings` out and remove all reference to the Google Meetings Tiles within the json.
> 
> Let me know how you go!
> 
> <img alt="image" width="1458" src="https://user-images.githubusercontent.com/18430086/255046960-69611d01-0616-4748-89a3-34286586c99b.png">

Apologies Allister looked into it further and it appears to be privacy issues with my Google Calendar thanks for taking a look at this! Also if you have the ability to integrate other calendars in your account that would be amazing!

**Comment by allister-grange** [comment]
No worries! 
> Also if you have the ability to integrate other calendars in your account that would be amazing!

Are you saying that you would like to see multiple Google calendars on one tile card? Or are you talking about other providers like Microsoft?
